### PR TITLE
Feature/decision tree headings

### PR DESCRIPTION
**Pull request by D34D10CK**
I made a new module called HeadingDetectionDTModule based on the current heading detection module.
It uses a decision tree to classify lines in two classes, paragraph or heading. The results are pretty bad but should improve once we have a larger dataset. Better feature engineering would probably help too.
The python scripts to build the dataset and train the model are in the "train" folder. The trained model is converted to javascript and saved in model.js. For ease of use I included the pretrained model in the module's folder. 

Annotation 2019-12-02 181728

### CODE REVIEW

**Comment by D34D10CK** [comment]
Since we use quite a few python scripts already, would'nt it be better to use pipenv to handle the dependencies instead of writing them to a readme?
Regarding the npm script, I did not include one because training the model would require a dataset that is not included in the repo anyways. For the training I used data from the benchmark which I did not want to include here.

**Comment by marianorodriguez** [comment]
+1 for handling python dependencies with pipenv! I will add a task to clubhouse to not forget it.

**Comment by D34D10CK** [comment]
I have added a readme, tell me if it's enough.

**Comment by aarohijohal** [comment]
> 
> 
> +1 for handling python dependencies with pipenv! I will add a task to clubhouse to not forget it.
> 
> but please! For now let's add this new dependencies to the README. Later we will take every python dependency there and move it to a Pipfile or something like that

There is a PR temporarily closed which does exactly this:
https://github.com/axa-group/Parsr/pull/238

It's awaiting modification/suggestion for the docker deployment of pipenv by @slallemand.

**Pull request merged**
