### PR TITLE
[Ghostscript] Using gs instead of convert for pdf -> tiff conversion. Resolves #20

### LINKED ISSUE #20: Use ghostscript instead of convert to generate intermediate TIFF files (from PDF) before extracting using tesseract
Currently with some specific documents, the PDF pre processing step (a call to convert that generates tiff files) can generate low resolution images. Theses images are then passed to tesseract and the results are quite bad.

We should make sure that:

- the target images are big enough to get good results from tesseract.
- the processing time is fast enough.

We had a look at calling ghostscript directly.
300 dpi seems well enough and Ghostscript is faster than Convert.

```
$ gs -dNOPAUSE -q -sDEVICE=tiff48nc -dBATCH -sOutputFile=a.tiff -r300 a.pdf -c quit
```

Note that this create some pretty huge files.

### PR DESCRIPTION
**Pull request by aarohijohal**
- Replaces imagemagick by Ghostscript to perform PDF -> TIFF conversion.
- One of the biggest advantage being that we can generate higher quality TIFFs, which is directly proportional to higher quality input to image extractors.

### CODE REVIEW

**Comment by slallemand** [comment]
@aarohijohal does it mean imagemagick is no more needed at all ?

**Comment by aarohijohal** [comment]
> @aarohijohal does it mean imagemagick is no more needed at all ?

We've always wanted to replace imagemagick with ghostscript to get higher quality results.
But I'm still keeping this PR as draft until we've talked about the licencing constraint (ghostscript is AGPL).
I will open it if it is not a constraint. If it is, we'll stick to imagemagick.

**Comment by slallemand** [comment]
ok thanks.
By the way, imagemagick already relies on gs if I'm not wrong

**Comment by aarohijohal** [comment]
Closing for now. Will reopen when relevant again.

**Pull request closed without merging**
